### ISSUE TITLE
Create test inputs to RNA-Seq pipeline

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil-scripts#1]
_From @jvivian on August 10, 2015 23:26_

null

_Copied from original issue: BD2KGenomics/toil#225_

**Comment by jvivian** [comment]
This was sort of a failure as I was able to find and create small fastqs but one step in the pipeline now takes 300x longer than it used to on these small files which is rather unintuitive.   Right now the smallest zipped sample we have is 7.5G and I'm timing a run on a 32 core machine.
