### ISSUE TITLE
Preconvert dbSNP site file to ADAM and store in S3

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/toil-scripts#104]
Right now, we convert the known sites file from VCF to ADAM on each run. We should just store it in the S3 bucket in ADAM format, as it'll be smaller, and will save us a minute of conversion time per run.

**Comment by almussel** [comment]
Which dbsnp file do we want to use for the ADAM test? Is it already in s3 in VCF format?

**Comment by fnothaft** [comment]
`s3://cgl-pipeline-inputs/variant_grch38/ALL_20141222.dbSNP142_human_GRCh38.snps.vcf`

**Comment by heuermh** [comment]
Perhaps I should pick this up, since I want a toil script to do this for other reasons

**Comment by heuermh** [comment]
I hacked this up but need to resolve some git stuff before creating a pull request
