### ISSUE TITLE
Adapt Kyle's CLIA supplied pipeline into his variant calling pipeline

### ISSUE THREAD

**Issue by benedictpaten** [BD2KGenomics/toil-scripts#11]

**Comment by jvivian** [comment]
Should I take point on contacting Kyle instead of waiting for him to email me?  I couldn't find his address in the OHSU directory and I'm not sure if he still has an soe account since he left.

**Comment by jvivian** [comment]
Emailed him Sept 4th (kellrott@soe.ucsc.edu) and have not received a response.

**Comment by jvivian** [comment]
Parameters were the same as when I last spoke with him, simply  `--tumor_lod 10`.
