### ISSUE TITLE
work_dir should be optional in docker_call

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/toil-scripts#111]
We pass CWD when using docker_call with Spark jobs, which seems a bit silly.

**Comment by heuermh** [comment]
This one
https://github.com/BD2KGenomics/toil-scripts/blob/master/src/toil_scripts/batch_alignment/bwa_alignment.py#L178

or should ```docker_call``` be moving to some util class?

**Comment by hannes-ucsc** [comment]
I've told at least three people to put their stuff into `toil_scripts/__init__.py` but I am worried that this will create unnecessary merge conflicts. Shall we start putting shared code into `toil_scripts/utils`, e.g  `toil_scripts/utils/docker.py` for docker related stuff?.

**Comment by fnothaft** [comment]
> but I am worried that this will create unnecessary merge conflicts.

As long as things are independent, they should be easy to resolve. I wouldn't worry too much, but:

> Shall we start putting shared code into toil_scripts/utils, e.g `toil_scripts/utils/docker.py` for docker related stuff?

Also SGTM.

**Comment by jvivian** [comment]
Ya, i have a PR I'm working on right now for a pipeline for doing alternative splicing analysis, and I've been exporting all the "general" functions to `__init__`.     I just made comments that separate the AWS , docker, job, and general functions. 

> As long as things are independent, they should be easy to resolve. I wouldn't worry too much, but:

I agree in some sense, but I've also been making modifications to a lot of these to make them simple and general purpose. I've seen a few that  get passed dictionaries where _specific_ key names are required, etc.  

In parallel, I'm also trying to write unit tests for all the functions I'm moving out.  Maybe I can coordinate with Hannes about breaking my PR up into a couple different ones, or what the best approach would be.

**Comment by fnothaft** [comment]
> I'd favor smaller PRs since this is a busy project ATM.

+1, small PRs were my assumption when I said:

> As long as things are independent, they should be easy to resolve.

**Comment by jvivian** [comment]
Resolved by common library refactoring
