### ISSUE TITLE
Dedup mess of duplicated functions in GATK pipelines

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/toil-scripts#112]
E.g., `docker_call`, `download_from_url`, other functions that just share a name, etc.

Many of these should be pulled out into a dedicated utils module, or something of that sort.

**Comment by jvivian** [comment]
@fnothaft, This one falls squarely on me.  Toil used to not support package structure, and as such, importing from a standard library didn't work.  Making this library will cause me to touch every pipeline, so  I'll confer with @hannes-ucsc and if he thinks it necessary we may call for a brief code moratorium while I make all the changes.

**Comment by fnothaft** [comment]
@jvivian No worries! We won't want to make this change until the ADAM recompute is done, so no rush on this. I'll be down at UCSC either next Thursday or Friday. Perhaps let's circle the wagons then?

**Comment by jvivian** [comment]
SG2M
