### ISSUE TITLE
Autoscaling code prints times as floating point numbers

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/toil-scripts#121]
E.g.,:

```
INFO: Using zone 'us-west-2a' and namespace '/not-a-real-namespace/'
02-29 01:14:32 :INFO:__main__:Cluster is 1 nodes as of 0.914703845978
```

Something to do with this [line](https://github.com/BD2KGenomics/toil-scripts/pull/114/files#diff-7060afbea50ff85e89fe57836bc27314R243). Not important to fix now, methinks, but we should clean it up at a later date.

Also, if the cluster is one node, we should print `1 node` not `1 nodes`. This is completely inconsequential, but is a pet peeve of mine.

**Comment by hannes-ucsc** [comment]
> pet peeve

I just do `node(s)`

Alternatively, there is

https://pypi.python.org/pypi/inflect

**Comment by almussel** [comment]
The offending line of code no longer exists.
