### ISSUE TITLE
Do we need to create a new toil-box on each new cluster creation?

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/toil-scripts#124]
Discussed on the call today between me and @hannes-ucsc. I thought we needed to create a new `toil-box` image whenever we registered a new key, @hannes-ucsc thinks we don't. TBD; we'll sort this out and fix it in the instructions later.

**Comment by hannes-ucsc** [comment]
The answer is "No". If you find this to be inaccurate, please reopen.
