### ISSUE TITLE
Modify überscript to run HG19 and GRCh38

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/toil-scripts#132]
@jpdna has reheadered the HG19 files, which means that we can now run the adam-vs-gatk überscript pipeline on both HG19 and GRCh38.

@jpdna can you:

* Add a file similar to https://github.com/BD2KGenomics/toil-scripts/blob/master/src/toil_scripts/adam_uberscript/input_files.py for HG19
* Modify the [überscript](https://github.com/BD2KGenomics/toil-scripts/blob/master/src/toil_scripts/adam_uberscript/adam_uberscript.py) to select between GRCh38 and HG19?

Once you open a PR with these changes, I, @hannes-ucsc, and @almussel will review. Once it looks good, we can kick off the 10 sample HG19 run. I'll add AIs for this on #113.

**Comment by jpdna** [comment]
PR #133 resolves this hopefully.

@fnothaft  - I want to now do a test run of this on the cluster.    Doing so should not  create any conflict with your runs given we are using seperate CGCLOUD namespaces, but wanted to double check with you before I start as if there is any danger  I'd wait.

**Comment by fnothaft** [comment]
Reopening this; @jpdna @hannes-ucsc the permissions for `s3://cgl-pipeline-inputs/variant_hg19_reordered` are screwy. We were using `https://` URLs, but the files aren't public and the AWS console won't let me make them public. I've [added a commit](https://github.com/fnothaft/toil-scripts/commit/591f63e2da0c0fac63b661fb4635a9b8b8dae74f) to #171 to WAR this, but it'd be good to have a second set of eyes on the issue.

**Comment by hannes-ucsc** [comment]
Probably ACLs that get in the way.

**Comment by fnothaft** [comment]
> Probably ACLs that get in the way.

Actually, the odd thing is that it looks like it is more the _absence_ of ACLs that is getting in the way.

**Comment by fnothaft** [comment]
This was resolved by #159.
