### ISSUE TITLE
Refactor codebase to a consistent case

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/toil-scripts#135]
Pet peeve of mine; we mix camelCase and snake_case in this repo.

I suggest we move to ALLCAPS or RanDOmCaSE. Really, ALLCAPS is the best of all worlds because it gives you all the satisfaction and warm feelings you get from writing Fortran, but with Python performance.

**Comment by hannes-ucsc** [comment]
Consensus is that toil-scripts should use PEP8 compliant naming.

**Comment by jvivian** [comment]
Not the case in my pipelines, but in ADAM pipelines.

**Comment by fnothaft** [comment]
As in, the ADAM pipelines are inconsistent?

**Comment by hannes-ucsc** [comment]
IIRC, consensus was that toil-scripts should be PEP-8 compliant as in `FooClass.bar_method()`. John says that his pipelines are compliant.

@almussel agreed to go over the Spark/ADAM pipelines to fix any potential non-PEP-8-compliance issues.

**Comment by jvivian** [comment]
> As in, the ADAM pipelines are inconsistent?

Sorry for being so unclear — I only meant that the ticket might've been opened for the ADAM pipelines as mine are all consistent.

**Comment by fnothaft** [comment]
> Sorry for being so unclear—I only meant that the ticket might've been opened for the ADAM pipelines as mine are all consistent.

Oh, yeah! That is correct.

> IIRC, consensus was that toil-scripts should be PEP-8 compliant as in FooClass.bar_method()

PEP-8 mixes cases? I don't often do this, but `¯\_(ツ)_/¯`.

In spite of my generally not being enthused with PEP-8, I agree with following PEP-8. We should document that somewhere, like in a `CONTRIBUTING.md`. ;)

**Comment by almussel** [comment]
@hannes-ucsc @fnothaft Should I check for all pep8 compliance (line lengths, trailing whitespace, etc.) or just for proper naming conventions?

**Comment by hannes-ucsc** [comment]
Just naming IMO. Before we have something that enforces PEP-8 on each build it doesn't make sense to do more thorough cleaning.
