### ISSUE TITLE
Sort Simons FASTQ files

### ISSUE THREAD

**Issue by jpdna** [BD2KGenomics/toil-scripts#139]
The BAM->FASTQ conversion using `samtools fastq -1 /data/output_1.fastq -2 /data/output_2.fastq -0 /data/output_0.fastq /data/mybam.bam` resulted in fastq files which were not sorted, so pairs did not line up between the two files.

I'm testing now sorting them using:
```
zcat LP6005441-DNA_A01_1.fastq.gz | paste - - - - | sort -k1,1 -S 10G -T temp/ |  tr '\t' '\n' | gzip > /sorted/LP6005441-DNA_A01_1.fastq.gz 
```
and if successful will run this sorting as a toil job, and update original BAM->FASTQ conversion code to sort by default.
I'll provide an example pair of files from a single sample ASAP for use in testing.

**Comment by fnothaft** [comment]
Thanks @jpdna! Indeed, BWA-MEM is processing the current files as single ended reads:

```
[M::mem_process_seqs] Processed 3200000 reads in 1058.497 CPU sec, 34.540 real sec
[M::process] read 3200000 sequences (320000000 bp)...
[M::process] 3200000 single-end sequences; 0 paired-end sequences
[M::mem_process_seqs] Processed 3200000 reads in 1072.141 CPU sec, 34.810 real sec 
```

**Comment by fnothaft** [comment]
Ah, also, can you make sure to get the NA12878 sample? We'll need that for the first recompute.

**Comment by jpdna** [comment]
> Ah, also, can you make sure to get the NA12878 sample? We'll need that for the first recompute

yup

**Comment by jpdna** [comment]
you will find now the first sorted pair of fastq files for a single sample at:
`s3://cgl-sgdd-work/sequence-sorted`
The read pairs  in the sorted file do  all match one-to-one on row basis as expected.  The files are confirmed to have the correct (same) number of rows post sorting.
I ran the first 2500 paired-reads (head -n 10000) through bwa mem like 
```
bwa mem -t 12 GRCh38_full_analysis_set_plus_decoy_hla.reordered.fa LP6005441-DNA_A01_1.sorted.fastq.head10000 LP6005441-DNA_A01_2.sorted.fastq.head10000
```
and output does refer to pairs, so all seems good.
I'm starting a big run shortly and the sorted files will begin appearing at `s3://cgl-sgdd-work/sequence-sorted`
@fnothaft - I will run NA12878 first and let you know when it is done and where to find

**Comment by jpdna** [comment]
The sorted NA12878 fastq files can be found at
```
s3://cgl-sgdd-work/NA12878/sequence/NA12878.mapped.ILLUMINA.bwa.CEU.high_coverage_pcr_free.20130906_1.fastq.gz
s3://cgl-sgdd-work/NA12878/sequence/NA12878.mapped.ILLUMINA.bwa.CEU.high_coverage_pcr_free.20130906_2.fastq.gz
```
Note: the path/filename is the same as the previous unsorted ones, but files have been replaced with the sorted ones

**Comment by jpdna** [comment]
Batch run seems to be going well.

Once Shane (or others) no longer need the unsorted files we should delete them to save space.  I'll leave a README there when they are deleted.    I'll plan to follow up with Shane on when he is done with them.  @hannes-ucsc  - do you no who else may have access and want to keep the unsorted files available?

**Comment by hannes-ucsc** [comment]
@jpdna, I asked that question on the email thread that raised this issue.

**Comment by fnothaft** [comment]
Thanks @jpdna! I'll start rerunning later this PM.
