### ISSUE TITLE
Make s3am block size parametrizable

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/toil-scripts#141]
Where given, s3am block size is hardcoded. E.g., https://github.com/BD2KGenomics/toil-scripts/blob/master/src/toil_scripts/rnaseq_cgl/rnaseq_cgl_pipeline.py#L873. This is a low priority.

**Comment by fnothaft** [comment]
Copying @hannes-ucsc's comment from #141:

> This will do for now but it would be nice to have three retries as in
>
> https://github.com/BD2KGenomics/toil-scripts/blob/master/src/toil_scripts/rnaseq_cgl/rnaseq_cgl_pipeline.py#L873

Even better: we should pull every s3am call out into a library call that wraps the retry count, encryption, etc.

**Comment by hannes-ucsc** [comment]
Use 64MB

**Comment by jpdna** [comment]
> Even better: we should pull every s3am call out into a library call that wraps the retry count, encryption, etc.
@hannes-ucsc - should I put this s3am wrapper library function in toil_scripts/__init__.py similar to https://github.com/BD2KGenomics/toil-scripts/blob/master/src/toil_scripts/__init__.py#L5  ?

**Comment by hannes-ucsc** [comment]
That library call exists now. It should default to passing 64MB  for `--part-size`.

**Comment by jvivian** [comment]
Won't fix — hardcoded as 50MB in common library and @hannes-ucsc deems that sufficient.
