### ISSUE TITLE
Download LAML samples (FireCloud)

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil-scripts#144]
LAML samples weren't processed during recompute due to being misclassified in CGHub.

**Comment by jvivian** [comment]
bucket: tcga-laml-data

**Comment by hannes-ucsc** [comment]
Ideally though, I want all of our buckets to start with cgl- if its not too
late ...

On Fri, Mar 4, 2016 at 5:01 PM, John Vivian <notifications@github.com>
wrote:

> bucket: tcga-laml-data
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BD2KGenomics/toil-scripts/issues/144#issuecomment-192540923>
> .
>



-- 
Hannes Schmidt
Software Engineer
Center for Biomolecular Science and Engineering
University of California, Santa Cruz

(206) 696-2316 (cell)
hannes@ucsc.edu

**Comment by jvivian** [comment]
Makes sense to me, but since the other TCGA bucket started with TCGA, that's how I tagged it, sorry =/
