### ISSUE TITLE
Make it easier to pass options via überscript

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/toil-scripts#147]
E.g., pipeline options (`-skip_alignment`), instance creation options (`-o etc_hosts ...`). We shouldn't have to add a new CLI option for each.

**Comment by hannes-ucsc** [comment]
`--pipeline-option=--skip_alignment`
`-P=--skip_alignment`
`--cgcloud-option=-O=etc_hosts_entries=foo=1.2.3.4`
`-C=-O=etc_hosts_entries=`

This is simple to implement and relatively easy to use. `--` would only work if there was one thing to forward options to. We have at least two. I've tried `nargs='+'` and `ARGPARSE_REMAINDER` and both have trouble with option arguments starting with dash.

**Comment by hannes-ucsc** [comment]
The überscript should take a JSON-like config similar to the one we are adding in #265 to address #242. It remains open if the pipeline configs should be nested in the überscript config.

**Comment by jvivian** [comment]
Fixed by config refactoring.
