### ISSUE TITLE
picard AddOrReplaceReadGroups fails unpredictibly

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/toil-scripts#151]
For whatever reason, when using [Picard](https://github.com/BD2KGenomics/cgl-docker-lib/tree/master/picardtools) to attach ReadGroups to our aligned files, this occasionally fails and instead of writing out the same BAM file as we started with, but with the new read group attached, it writes out a 30KB corrupt BAM file. This is obviously disappointing.

- [x] @fnothaft will WAR this using `bwa-kit`, which is actually what we should do anyways because rewriting a 150GB BAM file to add ~30B of ASCII text to the header is wasteful. (see #153)
- [ ] @almussel will debug _why_ this is happening with Picard? You can repro it by running the batch alignment pipeline on `LP6005441-DNA_A12` from the SGD project. (this issue)
- [ ] We should fix the garbage we're writing in the platform fields.
- [ ] We should close the gaps between the bwa and bwakit pipelines (see #154)

**Comment by fnothaft** [comment]
@jvivian is there a reason we're writing garbage metadata into the headers? I'm pretty sure not all data is being sequenced on [machine 12345](https://github.com/BD2KGenomics/toil-scripts/blob/master/src/toil_scripts/batch_alignment/bwa_alignment.py#L511).

**Comment by jvivian** [comment]
@fnothaft Yes. GATK _requires_ the PU field. The samples I was initially aligning did not have sequence machine info and that was a placeholder that never got put into argparse (my fault).  Should I fix that on a different branch?

```
These parameters need to be used

RGLB=String
LB=String                     Read Group Library  Required.

RGPU=String

PU=String                     Read Group platform unit (eg. run barcode)  Required.

RGSM=String
SM=String                     Read Group sample name  Required.
```

**Comment by fnothaft** [comment]
> @fnothaft will WAR this using bwa-kit, which is actually what we should do anyways because rewriting a 150GB BAM file to add ~30B of ASCII text to the header is wasteful.

#153

**Comment by fnothaft** [comment]
> @fnothaft Yes. GATK requires the PU field.

SRSLY? AH MAH ZING.

> The samples I was initially aligning did not have sequence machine info and that was a placeholder that never got put into argparse (my fault). Should I fix that on a different branch?

Ah yes, this is thorny now. Let me put a junk PU into #153.

I'd prefer to not have a proliferation of things into the argument parser. It's kinda limiting --> we're OK as long as our samples are single read group samples\*. Perhaps we could ask the user to provide "read group dictionary" files? Also, is it just me or is everything in bioinformatics broken? I feel a great sense of existential dread every time I stumble across something like this...

\* I don't think our current SGDP samples are, but alas the BAM files we've got insist that they are. But, it's hard to generate 100GB of sequence data from a single sequencer lane/run, so I'm pretty confident they're wrong.

**Comment by jvivian** [comment]
> I'd prefer to not have a proliferation of things into the argument parser. It's kinda limiting 
Ok, my go-to is to hide stuff like this in a default argument, but if that's not your preferred design choice I'm open to whatever. 

> Also, is it just me or is everything in bioinformatics broken? I feel a great sense of existential dread every time I stumble across something like this...

That is why I bought beer on my way home.

**Comment by fnothaft** [comment]
> Ok, my go-to is to hide stuff like this in a default argument, but if that's not your preferred design choice I'm open to whatever.

Yeah, I just don't think it makes sense to do that here because you'd expect to have many RGs per sample, with possibly different library settings. If you're running a lot of samples in batch, you'd possibly have different PU's per sample (e.g., I maxed out the ol' Amex and bought me a fleet of X10's and now I am sequencing everything that has DNA).

> That is why I bought beer on my way home.

There is not enough, nor strong enough beer for my sorrows. Bioinformatics is truly a sorrow that lingers. ;)

I swear, at the end of this sprint (I don't know if you can really call it a sprint though after 4 months?), I will drink 1000 beers and forget what I have done.

**Comment by hannes-ucsc** [comment]
Maybe Picard was written under pressure to get a paper out the door and no one ever came back to fix all the shortcuts that had to be taken to meet the deadline.

**Comment by fnothaft** [comment]
> Maybe Picard was written under pressure to get a paper out the door and no one ever came back to fix all the shortcuts that had to be taken to meet the deadline.

They've never published a paper about Picard, which makes it great to cite in papers...

**Comment by heuermh** [comment]
> Also, is it just me or is everything in bioinformatics broken?

Not everything is.  But if you want to point fingers I have just the t-shirt for you.

**Comment by fnothaft** [comment]
This was resolved by https://github.com/BD2KGenomics/toil-scripts/commit/1a9a644bf5a152fc049fb792a3276d831a442964#diff-edaec62e95d22c39dec02f323c5c3e6a.
