### ISSUE TITLE
Rationalize differences between bwa and bwa-kit pipelines

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/toil-scripts#154]
The bwa and bwa-kit pipelines used to share 3 out of 4 pipeline stages in `toil_scripts.batch_alignment.bwa_alignment`, but now they just share 1. Should we separate them out, consolidate them in some other way, etc...?

CC @jvivian for comment

**Comment by jvivian** [comment]
@fnothaft 

What features does the bwa method provide that you don't get in the bwa-kit?  If the answer is none, I'd vote we deprecate the script to the "ol' alignment script" graveyard and only use bwa-kit.

**Comment by fnothaft** [comment]
So like, philosophically, I _really dislike_ bwa-kit because it is a proprietary binary distro of bwa (e.g., alt-aware alignment only works with the bwa-kit distro). Otherwise, it's really convenient. You may be right; it might be a good idea just to deprecate `bwa` though so that we have fewer moving parts.

**Comment by jvivian** [comment]
>  because it is a proprietary binary distro 

Doesn't that describe Picard?

**Comment by fnothaft** [comment]
>> because it is a proprietary binary distro
>Doesn't that describe Picard?

We build Picard from source, no? I've always used Picard built from source, at least...

Some of the functionality in `bwakit` actually _can not_ be built from source. E.g., the [alt aware alignment](https://github.com/lh3/bwa/blob/master/README-alt.md) code depends on a JS interpreter that [doesn't run when built by hand (it segfaults immediately)](https://github.com/BD2KGenomics/cgl-docker-lib/pull/76), thus `bwakit` has a hand-modded build, AFAIK.

**Comment by jvivian** [comment]
My mistake.  My vote is still for the simpler method (which I'm assuming is also a bit faster).

**Comment by hannes-ucsc** [comment]
We fully switched to bwa-kit.
