### ISSUE TITLE
Cleanup BWA launch script

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil-scripts#156]
mesos launch script should not have `--output_dir` set by default, especially writing to `/home/mesosbox/shared`.

**Comment by hannes-ucsc** [comment]
Keep in mind that Toil 3.2.0 will have a reasonable default for --workDir that will put it on ephemeral.
Consider adding a comment that signifies argument as a stop-gap and that it should be removed.

**Comment by jvivian** [comment]
@hannes-ucsc , I mistyped `--output_dir` somehow.  Sorry, `--workDir` is set to /var/lib/toil already.
