### ISSUE TITLE
ADAM überscript: Do not use cgcloud's --share to distribute toil-scripts to workers

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil-scripts#160]
Not needed and potentially dangerous because it could conflict with Toil's built-in hot deployment

**Comment by fnothaft** [comment]
I thought we were just rsync'ing to the toil leader. Where's this going on?

**Comment by jvivian** [comment]
> Where's this going on?

I wasn't aware that was our current procedure and I misinformed one of our production members.  

@fnothaft -- Do you guys just clone toil-scripts to /home/mesosbox on the leader?  I want to add that step to cluster setup in my uber script.

**Comment by fnothaft** [comment]
> @fnothaft -- Do you guys just clone toil-scripts to /home/mesosbox on the leader? I want to add that step to cluster setup in my uber script.

Yeah, we do a clone but not to the leader, we do it to the head node (generic-ubuntu-trusty-box). See here: https://github.com/BD2KGenomics/toil-scripts/blob/master/src/toil_scripts/adam_uberscript/README.md

**Comment by jvivian** [comment]
Ah I see, wouldn't have that of doing it that way. Thanks for the example.

**Comment by almussel** [comment]
We are not currently using the --share option to cgcloud. We are using rsync to put the scripts on the toil-leader. That directory is being passed to the uberscript using an option --share that should be renamed.

**Comment by jvivian** [comment]
> using the --share option to cgcloud.

The production team has to use `--share` to pass in the master encryption key and configuration file, so initially I thought I was saving a step by piggybacking off of that .

**Comment by hannes-ucsc** [comment]
Yes. So let's rename the überscript parameter from `--share` to `--toil-scripts`. There should be no need to use cgcloud's `--share` for Spark/ADAM. It should only be used for files that need to be present on a worker as soon as it comes up. The toil-scripts repository is not one of these things because it get hot-deployed by Toil.
