### ISSUE TITLE
Pickling fails in adam_gatk_pipeline

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/toil-scripts#162]
Some issue with a promise not getting picked properly, tbd.

```
WARNING:toil.leader:9a29c6ce-7fc8-42b8-8c14-faaa2032e4c5:         File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1200, in _serialiseJob
WARNING:toil.leader:9a29c6ce-7fc8-42b8-8c14-faaa2032e4c5:       PicklingError: Can't pickle <type 'instancemethod'>: attribute lookup __builtin__.instancemethod failed
```

**Comment by fnothaft** [comment]
This isn't in the GATK portion.

**Comment by fnothaft** [comment]
Our culprit is the promise [here](https://github.com/BD2KGenomics/toil-scripts/blob/master/src/toil_scripts/adam_pipeline/adam_preprocessing.py#L253). Oddly enough, if you move the promise into the `wrapJobFn` call, all is good, all is well. @hannes-ucsc @jvivian is this an expected limitation of the serialization used in toil?

I'll have a PR with this fix shortly. I'm just letting it run through.

**Comment by hannes-ucsc** [comment]
And no, there is no Toil-imposed limit to promised values. They are just files in the job store. I don't know about pickle's limitations.

**Comment by fnothaft** [comment]
> Probably obvious , but the line you link to should have pr() instead of pr.

Yeah, it's more insidious than that though.

**Comment by hannes-ucsc** [comment]
In that case you should get a different stack trace. The fragment you posted above is indicative of the missing parentheses.

**Comment by fnothaft** [comment]
> In that case you should get a different stack trace. The fragment you posted above is indicative of the missing parentheses.

Yes, that is correct, but adding the parens just points out more errors, hence my "insidious" comment.

**Comment by hannes-ucsc** [comment]
Feel free to post the new trace.

**Comment by fnothaft** [comment]
It's not a trace per se. This is what I was talking about in scrum; we build the service job DAG in a way that makes it terminate before the jobs it is servicing run, etc. Architectural issues.
