### ISSUE TITLE
Generate MD5s for Simons fastq files

### ISSUE THREAD

**Issue by jpdna** [BD2KGenomics/toil-scripts#163]
Plan to generate MD5 for the *.fastq.gz  ( not uncompressed ) unless anyone objects.

**Comment by hannes-ucsc** [comment]
If you need to download them for computing the checksum, that would be sort of pointless.

**Comment by hannes-ucsc** [comment]
> I figure my downloading from S3 to EC machine to generate md5 serves as validation that when someone from Sanger downloadd they get same thing

Not true if the error was introduced during upload.

> I have higher confidence that s3am uploaded without error so I am not so concerned about the integrity

What evidence drives that confidence and why does a degree of confidence lead to a absolute lack of concern?

**Comment by hannes-ucsc** [comment]
Scratch the second one. I misread.

**Comment by jpdna** [comment]
Nah - indeed I am still concerned sitting here thinking of it, and no good reason for assuming integrity of s3am upload.
I'll go ahead and do a validation run, in doing so I'll generate MD5 both for uncompressed fastq and also for the gzipped fastq.  Ought to have done that in the first place.

**Comment by hannes-ucsc** [comment]
I agree. When you do that, in fact, the downloaded input's checksum should also be validated. I'm getting paranoid with that one person saying some of the parts in some of the files were "hard" to download, or took a long time.

**Comment by jpdna** [comment]
There are 8 files listed below which show a MD5 discrepancy.
These are being regenerated and validated now
```
LP6005441-DNA_A06_1.fastq
LP6005441-DNA_A06_2.fastq
LP6005441-DNA_B06_1.fastq
LP6005441-DNA_B06_2.fastq
LP6005441-DNA_C06_1.fastq
LP6005441-DNA_C06_2.fastq
LP6005441-DNA_D05_1.fastq
LP6005441-DNA_D05_2.fastq
```

**Comment by jpdna** [comment]
The above 8 files failed to validate  almost certainly due to out of disk error, they are the highest outliers for input file size and calculations look like these could indeed just exceed the limit.  This left slightly different truncated files in different runs leading to the MD5 discrepancy - I will replicate the error  just to be sure.

I've changed instance types used so that this won't be a problem, and they are running now.

I've put in the needed exception handling to the  bam->fastq generation code so that the exception would be properly caught and not silently produce a truncated file.   

While it is very likely that the rest of the generated fastq files are fine given that they did not produce the MD5 errors upon multiple runs that brought these 8 to attention, and Shane reported these same 8.   HOWEVER, I am concerned with  the fact that these 8 were not detected earlier due to the exception not being caught.  I am worried there could be some other mode of undetected file truncation or other error  that the  revised error handling could now catch.   

To eliminate this lingering doubt - I am going to re-run the fastq generation to produce md5s which I can validate one final time prior to reporting this issue as resolved.

**Comment by hannes-ucsc** [comment]
@jpdna, feel free to reopen if this isn't actually done.
