### ISSUE TITLE
RSEM error rna-seq-unc pipeline

### ISSUE THREAD

**Issue by dyollluap** [BD2KGenomics/toil-scripts#164]
Current setup:
toil-box (stable release, toil 3.1.4), new image March 6.
--single_end_reads option is the only different thing. 

All the samples failed on this point:

WARNING:toil.leader:The jobWrapper seems to have left a log file, indicating failure: 1f870551-e2ea-4b41-a5a3-1c30c789f478
WARNING:toil.leader:Reporting file: 1f870551-e2ea-4b41-a5a3-1c30c789f478
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:       ---TOIL WORKER OUTPUT LOG---
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:       Archive:  /var/lib/toil/tmpPu72JU/localTempDir/ttQt765/rsem_ref.zip
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:          creating: /var/lib/toil/tmpPu72JU/localTempDir/ttQt765/rsem_ref/
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:         inflating: /var/lib/toil/tmpPu72JU/localTempDir/ttQt765/rsem_ref/prep_ref.log
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:         inflating: /var/lib/toil/tmpPu72JU/localTempDir/ttQt765/rsem_ref/hg19_M_rCRS_ref.transcripts.fa
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:         inflating: /var/lib/toil/tmpPu72JU/localTempDir/ttQt765/rsem_ref/unc_hg19.gtf
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:         inflating: /var/lib/toil/tmpPu72JU/localTempDir/ttQt765/rsem_ref/hg19_M_rCRS_ref.seq
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:         inflating: /var/lib/toil/tmpPu72JU/localTempDir/ttQt765/rsem_ref/hg19_M_rCRS_ref.idx.fa
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:         inflating: /var/lib/toil/tmpPu72JU/localTempDir/ttQt765/rsem_ref/hg19_M_rCRS_ref.grp
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:         inflating: /var/lib/toil/tmpPu72JU/localTempDir/ttQt765/rsem_ref/unc_knownToLocus.txt
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:         inflating: /var/lib/toil/tmpPu72JU/localTempDir/ttQt765/rsem_ref/hg19_M_rCRS.fa
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:         inflating: /var/lib/toil/tmpPu72JU/localTempDir/ttQt765/rsem_ref/hg19_M_rCRS_ref.ti
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:         inflating: /var/lib/toil/tmpPu72JU/localTempDir/ttQt765/rsem_ref/hg19_M_rCRS_ref.chrlist
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:       rsem-parse-alignments /data/rsem_ref/hg19_M_rCRS_ref rsem.temp/rsem rsem.stat/rsem b /data/filtered.bam -t 0 -tag XM -q
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:       rsem-build-read-index 32 0 1 rsem.temp/rsem_alignable.fa
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:       Cannot open rsem.temp/rsem_alignable.fa! It may not exist.
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:       "rsem-build-read-index 32 0 1 rsem.temp/rsem_alignable.fa" failed! Plase check if you provide correct parameters/options for the pipeline!
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:       Traceback (most recent call last):
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:         File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 273, in main
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:           fileStore=fileStore)
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:         File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1294, in _execute
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:           returnValues = self.run(fileStore)
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:         File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1400, in run
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:           rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:         File "/home/mesosbox/shared/AWSkeyConfig/toil-scripts/src/toil_scripts/rnaseq_unc/rnaseq_unc_pipeline.py", line 778, in rsem
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:           tool_parameters=parameters, work_dir=work_dir, sudo=sudo)
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:         File "/home/mesosbox/shared/AWSkeyConfig/toil-scripts/src/toil_scripts/rnaseq_unc/rnaseq_unc_pipeline.py", line 280, in docker_call
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:           raise RuntimeError('docker command returned a non-zero exit status. Check error logs.')
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:       RuntimeError: docker command returned a non-zero exit status. Check error logs.
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:       Exiting the worker because of a failed jobWrapper on host ip-172-31-29-55
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:       ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host ip-172-31-29-55
WARNING:toil.leader:1f870551-e2ea-4b41-a5a3-1c30c789f478:       WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job 1f870551-e2ea-4b41-a5a3-1c30c789f478 to 0
WARNING:toil.leader:Job: 1f870551-e2ea-4b41-a5a3-1c30c789f478 is completely failed
INFO:toil.leader:Reissued any over long jobs

**Comment by dyollluap** [comment]
Also now getting a similar error at same point on the CGL RNA-seq pipeline, I'll post a separate issue.

**Comment by jvivian** [comment]
I've checked and the RSEM method for handling single-end data is identical to CGL method, which works.  If this issue comes up again please re-open, although ideally most future samples will be run on the CGL pipeline which is much easier to debug.
