### ISSUE TITLE
RSEM error rna-seq-cgl pipeline

### ISSUE THREAD

**Issue by dyollluap** [BD2KGenomics/toil-scripts#165]
I'm getting another RSEM error that looks similar (more details on stacktrace) to the unc pipeline RSEM error... same setup. I notice there's RuntimeError line that includes a --paired-end option in the status. These are single end fastq. 

WARNING:toil.leader:The jobWrapper seems to have left a log file, indicating failure: e07acfb1-22fb-41d6-8be2-5222ff62e7de
WARNING:toil.leader:Reporting file: e07acfb1-22fb-41d6-8be2-5222ff62e7de
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	---TOIL WORKER OUTPUT LOG---
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	starIndex/
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	starIndex/exonInfo.tab
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	starIndex/SA
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	starIndex/chrNameLength.txt
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	starIndex/sjdbInfo.txt
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	starIndex/Genome
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	starIndex/transcriptInfo.tab
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	starIndex/SAindex
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	starIndex/sjdbList.out.tab
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	starIndex/geneInfo.tab
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	starIndex/chrStart.txt
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	starIndex/chrName.txt
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	starIndex/chrLength.txt
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	starIndex/sjdbList.fromGTF.out.tab
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	starIndex/genomeParameters.txt
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	starIndex/exonGeTrInfo.tab
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	Mar 10 22:03:02 ..... Started STAR run
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	Mar 10 22:03:02 ..... Loading genome
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	Mar 10 22:03:35 ..... Started mapping
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	Mar 10 22:07:48 ..... Started sorting BAM
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	Mar 10 22:11:20 ..... Finished successfully
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	rsem_ref_hg38/
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	rsem_ref_hg38/hg38.seq
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	rsem_ref_hg38/hg38.fa
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	rsem_ref_hg38/hg38.n2g.idx.fa
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	rsem_ref_hg38/hg38.chrlist
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	rsem_ref_hg38/gencode.v23.annotation.gtf
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	rsem_ref_hg38/hg38.grp
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	rsem_ref_hg38/hg38.idx.fa
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	rsem_ref_hg38/hg38.transcripts.fa
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	rsem_ref_hg38/hg38.ti
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	rsem-parse-alignments /data/rsem_ref_hg38/hg38 rsem.temp/rsem rsem.stat/rsem b /data/transcriptome.bam -t 2 -tag XM -q
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	rsem-build-read-index 32 0 1 rsem.temp/rsem_alignable_1.fa rsem.temp/rsem_alignable_2.fa
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	rsem-run-em /data/rsem_ref_hg38/hg38 2 rsem rsem.temp/rsem rsem.stat/rsem -p 16 -b b /data/transcriptome.bam 0 -q
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	No valid read to estimate the length distribution!
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	"rsem-run-em /data/rsem_ref_hg38/hg38 2 rsem rsem.temp/rsem rsem.stat/rsem -p 16 -b b /data/transcriptome.bam 0 -q" failed! Plase check if you provide correct parameters/options for the pipeline!
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	Traceback (most recent call last):
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	  File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 273, in main
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	    fileStore=fileStore)
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1294, in _execute
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	    returnValues = self.run(fileStore)
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1400, in run
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	  File "/home/mesosbox/shared/AWSkeyConfig/toil-scripts/src/toil_scripts/rnaseq_cgl/rnaseq_cgl_pipeline.py", line 738, in rsem
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	    tool_parameters=parameters, work_dir=work_dir, sudo=sudo)
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	  File "/home/mesosbox/shared/AWSkeyConfig/toil-scripts/src/toil_scripts/rnaseq_cgl/rnaseq_cgl_pipeline.py", line 256, in docker_call
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	    raise RuntimeError('docker command returned a non-zero exit status: {}'.format(tool_parameters))
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	RuntimeError: docker command returned a non-zero exit status: ['--paired-end', '--quiet', '--no-qualities', '-p', '16', '--forward-prob', '0.5', '--seed-length', '25', '--fragment-length-mean', '-1.0', '--bam', '/data/transcriptome.bam', '/data/rsem_ref_hg38/hg38', 'rsem']
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	Exiting the worker because of a failed jobWrapper on host ip-172-31-21-98
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host ip-172-31-21-98
WARNING:toil.leader:e07acfb1-22fb-41d6-8be2-5222ff62e7de:	WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job e07acfb1-22fb-41d6-8be2-5222ff62e7de to 1

**Comment by jvivian** [comment]
Given the file names I saw and the amount of single-end data processed during the recompute I'm going to go ahead and close this for now.
