### ISSUE TITLE
Create Toil script with service jobs for ADAM

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil-scripts#17]
Should have one service for the Spark master and N services for the slaves. @fnothaft mentioned using a separate container for the Tachyon master. Until @fnothaft or @heuermh deliver the corresponding containers, the actual `docker` invocations should be stubbed out.

**Comment by fnothaft** [comment]
I should have the containers coming at you this PM.

**Comment by heuermh** [comment]
Closed by #72?

**Comment by fnothaft** [comment]
Yes, closed by #72.
