### ISSUE TITLE
Cluster shrinker is... bloodthirsty

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/toil-scripts#172]
I've been having an enjoyable experience recently, as the cluster shrinking code from the überscript has gone all Jason Voorhees and my toil-workers are being cut down in the streets, in front of my own, persistently weepy eyes.

There are two problems that I am aware of:

* Our [CPU utilization threshold](https://github.com/BD2KGenomics/toil-scripts/blob/master/src/toil_scripts/adam_uberscript/adam_uberscript.py#L326) is unrealistically high (50%). Some of our pipeline stages are IO bound (MarkDups pegs I/O while keeping CPU ~25%, IIRC), and also we have nodes chilling around without doing a ton of work (i.e., the Spark masters). This is easy to fix.
* We are killing nodes when we are at our requested cluster size. There's a [conditional that checks this](https://github.com/BD2KGenomics/toil-scripts/blob/master/src/toil_scripts/adam_uberscript/adam_uberscript.py#L404), but for some reason, this isn't firing properly. I've added logging to debug this. This manifests as:
 * We bump the node count.
 * We don't decrease the node count.
 * ...
 * The autoscaler kills off the idle nodes, and immediately restarts them to bring the cluster up to desired size.
 * PROFIT! (LOSS?)

**Comment by jvivian** [comment]
> Our CPU utilization threshold is unrealistically high (50%)

Dang, I used 1% for our run.

**Comment by fnothaft** [comment]
>> Our CPU utilization threshold is unrealistically high (50%)
>
> Dang, I used 1% for our run.

Hah yeah, I've set it down to the 1%-5% range now. I'm more concerned about the conditional that is getting evaluated wrongly.

**Comment by fnothaft** [comment]
> We are killing nodes when we are at our requested cluster size. There's a conditional that checks this, but for some reason, this isn't firing properly. I've added logging to debug this. This manifests as:

Boom! This is an off-by-one error (sorta due to [this](https://github.com/BD2KGenomics/toil-scripts/commit/f50b8b13e8d2f31812b8163174dce006d8a08fce#diff-7060afbea50ff85e89fe57836bc27314) only being applied in one place) coupled with something that seems to be a race (it isn't clear that https://github.com/BD2KGenomics/toil-scripts/blob/master/src/toil_scripts/adam_uberscript/adam_uberscript.py#L407 blocks).
