### ISSUE TITLE
BQSR result size is too large

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/toil-scripts#177]
Bigger than `spark.driver.maxResultSize`:

```
WARNING:toil.leader:7337aec6-1c64-41ff-8684-46c35d624c08:       org.apache.spark.SparkException: Job aborted due to stage failure: Total size of serialized results of 247 tasks (1024.4 MB) is bigger than spark.driver.maxResultSize (1024.0 MB)
```

Almost all of the time it is by 5 damned MB.

**Comment by heuermh** [comment]
Do we just have to bump ```spark.driver.maxResultSize``` here?
https://github.com/BD2KGenomics/toil-scripts/blob/master/src/toil_scripts/adam_pipeline/adam_preprocessing.py#L111

**Comment by fnothaft** [comment]
Yeah, that's what I was going to do. Simplest sol'n.
