### ISSUE TITLE
Create dummy encryption key for toil-scripts unit tests

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil-scripts#192]
Upload a dummy test file with that encryption key.  Encryption key will go on Jenkins server once CI is setup.

**Comment by hannes-ucsc** [comment]
Wouldn't it be simpler to create a new key for every test run?

**Comment by hannes-ucsc** [comment]
... as part of the test setup, I mean.

**Comment by jvivian** [comment]
> Wouldn't it be simpler to create a new key for every test run? 

Not sure I understand -- The test is for downloading an encrypted file from S3, so I figured we'd have a permanent test file in S3 along with an associated encryption key for that file.

**Comment by hannes-ucsc** [comment]
The purist would say that tests should depend on as few external resources as possible. So ideally, the test setup should create the test file. Don't you have an function for uploading? If so, you could combine the upload and download function into a single test. And if not, it might still make sense to hardcode the key in the code and write it out to disk during test setup.

**Comment by jvivian** [comment]
Ok cool, I'll work on that.

**Comment by jvivian** [comment]
Will be resolved in #190

**Comment by hannes-ucsc** [comment]
#190 should refer to this using

```
Resolves #192
```

in the body (the first comment) or 

```
resolves #192
```

in the title.
