### ISSUE TITLE
Why are we checking node CPU utilization for nodes we don't want?

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/toil-scripts#195]
I was looking at some metrics logs and just wanted to understand the logic in the autoscaling script. When we decrease our node request, we only stop the nodes whose CPU utilization is low. Is this meant as a proxy for "which nodes are still running jobs?" Would it be possible to replace this with querying mesos to find out which nodes our jobs are running on?

**Comment by hannes-ucsc** [comment]
> Is this meant as a proxy for "which nodes are still running jobs?

Yes

> Would it be possible to replace this with querying mesos to find out which nodes our jobs are running on?

Probably. But Toil auto-scaling will take care of this. So I wouldn't botther.

**Comment by fnothaft** [comment]
> Probably. But Toil auto-scaling will take care of this. So I wouldn't bother.

SGTM. Closing...
