### ISSUE TITLE
SGDD buckets are lacking README and manifest

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil-scripts#196]
Both cgl-sgdd-reorg and cgl-sgdd-work buckets are lacking manifests and README.

The README should explain the provenance of the data and the directory layout. The manifest should list the checksums of all files.

Let me know if I am missing something here ...

**Comment by jpdna** [comment]
cgl-sgdd-reorg  files have *.md5 files in parallel to the files.
But certainly I can make a manifest file listing all files also with the MD5 checksums too , do you have an example specific format that the manifest should conform to?

I will do the same for cgl-sgdd-work, which is goal of #163

**Comment by hannes-ucsc** [comment]
My mistake re MD5's. My preference is using S3 object metadata, then .md5 files, then manifests. So we should be good once the .md5 files show up in cgl-sgdd-work.

So we just the READMEs briefly explaining the directory structure, file naming conventions and provenance of the files. 

But let me know if I am not making sense.

**Comment by hannes-ucsc** [comment]
Obsoleted by FireCloud disaster.
