### ISSUE TITLE
Add QC step to variant pipeline

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil-scripts#20]

**Comment by jvivian** [comment]
Will add stats via this tool:
http://broadinstitute.github.io/picard/command-line-overview.html#CollectAlignmentSummaryMetrics

-[ ] Test QC tool
-[ ] Add to variant pipeline

Where to put QC output?  tarball QC in a subdir along with the .vcf?

**Comment by jvivian** [comment]
We've agreed that this QC step should be [SnpEff](http://snpeff.sourceforge.net/index.html)

I have made a companion ticket to containerize SnpEff

**Comment by jvivian** [comment]
- [ ] Test SnpEff
- [ ] Add to variant pipeline

**Comment by melissacline** [comment]
What I'm hearing now is that the best QC is to run two or more different variant callers and look at their intersection.  Josh recommends MuSe, and says that Kyle was working on a Dockerized version.  BAMStats looks like it will be useful for the inevitable questions on why a variant was called by one caller and not another, as coverage and quality scores tend to be the type of heuristics that differentiate callers.  So, once SnpEff is squared away, let's look at MuSe, and BAMStats after that.

**Comment by hannes-ucsc** [comment]
Dupe of BD2KGenomics/driver-projects#25

**Comment by melissacline** [comment]
Closing BD2KGenomics/driver-projects#25

**Comment by jvivian** [comment]
@melissacline I feel like this is a stale ticket -- As we await feedback on the toil recompute should I close this ticket until we have something more concrete laid out?

**Comment by jvivian** [comment]
Closing in light of our scrum discussion from the other day.   I will be presented with a list of QC steps or warnings to produce from the pipeline (written to a WARNING.txt in output).
