### ISSUE TITLE
Releases 1.0

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil-scripts#200]
Test production pipelines
- [x] CGL
- [x] UNC
- [x] BWA
- [x] Exome

**Comment by jvivian** [comment]
Tested CGL.  UNC and BWA tests are running now.    

Paul offered to test the exome pipeline.

**Comment by fnothaft** [comment]
The `bwakit` side of the BWA pipeline definitely works. Don't know if that is sufficient for your test.
