### ISSUE TITLE
rnaseq_cgl_pipeline.py requires toil_scripts

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/toil-scripts#201]
When I try to run `launch_cgl_mesos.sh` from toil-master, I get
`/usr/bin/python: No module named toil_scripts.rnaseq_cgl`

How do I install toil-scripts ?

**Comment by jvivian** [comment]
Are you git cloning the entire toil-scripts repo onto the master?  The top line in the launch script should be adding toil-scripts/src to the PYTHONPATH

`export PYTHONPATH=$(python -c 'from os.path import abspath as a, dirname as d;import sys;print d(d(d(a(sys.argv[1]))))' $0)`

I clone the repo, then call the launch script:    
`./toil-scripts/src/toil_scripts/rnaseq_cgl/launch_cgl_mesos.sh`

**Comment by Jeltje** [comment]
Why would I want to clone the full repo if I only need two scripts? Is that a new way of doing things?

**Comment by Jeltje** [comment]
I git clone to a local directory, then `cgcloud ssh` the things I need.

I guess ssh to the master, then git clone wouldn't be any harder than what I'm doing.

**Comment by jvivian** [comment]
> Why would I want to clone the full repo if I only need two scripts?

So you can import functions from other scripts, common libraries, etc. This is an ongoing effort to minimize the amount of duplicated code that's in every script: https://github.com/BD2KGenomics/toil-scripts/pull/190

**Comment by Jeltje** [comment]
Makes sense. Outside the scope of this ticket, but I would like a way to set up a toil cluster with all necessary requirements (s3am, git...)

**Comment by hannes-ucsc** [comment]
Either 

`cgcloud ssh toil-leader git clone https://.../toil-scripts`

or 

`git clone https://.../toil-scripts  && rsync toil-leader -av toil-scripts :`

**Comment by hannes-ucsc** [comment]
> Outside the scope of this ticket, but I would like a way to set up a toil cluster with all necessary requirements (s3am, git...)

I would do this by writing a cgcloud plugin that extends ToilBox (and hence toil-box) with whatever software you need. This is (insufficiently) documented here

https://github.com/BD2KGenomics/cgcloud/blob/master/core/README.rst#customization
