### ISSUE TITLE
TASK LOST errors from toil

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/toil-scripts#202]
`./toil-scripts/src/toil_scripts/rnaseq_cgl/my_cgl_mesos.sh`
where the only difference between that and `launch_cgl_mesos.sh` is the name of the name of the run folder (jeltje-cgl-run-2)
I get repetitions of this error:

```
WARNING:toil.leader:No log file is present, despite jobWrapper failing: 02a113e4-9672-4e4c-993f-7fdb9fb4f503
WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job 02a113e4-9672-4e4c-993f-7fdb9fb4f503 to 1
INFO:toil.batchSystems.mesos.batchSystem:Preparing to launch Mesos task 8 using offer 2ced73c1-7344-4a2f-bbde-2862dfeb9c6f-O751...
INFO:toil.batchSystems.mesos.batchSystem:...launching Mesos task 8
WARNING:toil.batchSystems.mesos.batchSystem:Task 8 is in unexpected state TASK_LOST with message 'Executor terminated'
WARNING:toil.leader:Batch system is reporting that the jobWrapper with batch system ID: 8 and jobWrapper store ID: 02a113e4-9672-4e4c-993f-7fdb9fb4f503 failed with exit value 255
```
I killed it when it got up to 
`INFO:toil.batchSystems.mesos.batchSystem:...launching Mesos task 5123`

Complete error file is [here](http://hgwdev.cse.ucsc.edu/~jeltje/toil/cgl.err)
Near the top of that file is the somewhat worrisome
```
INFO:toil.job:Downloading entire JobStore
INFO:toil.job:0 jobs downloaded.
```

Let me know if it would be helpful to run with --logdebug

**Comment by hannes-ucsc** [comment]
I would run the script again and scan `/var/lib/mesos` on a worker for `*.err` and `*.out` files. Might be `*.stderr` and `*.stdout`. If you have multiple workers you need to scan the worker on which the lost task occurred or all of them if you don't know which worker. Hopefully, those files will contain more info on why the executor died.

**Comment by Jeltje** [comment]
Ah, this is our old friend
`pkg_resources.DistributionNotFound: The 'bd2k-python-lib==1.10.dev6'`
and that would be because I ran pip install s3am on the workers, as required by 
[the readme](https://github.com/BD2KGenomics/toil-scripts/blob/master/src/toil_scripts/rnaseq_cgl/README.md)

**Comment by hannes-ucsc** [comment]
While those instructions are generally correct, they don't take into account that cgcloud automatically installs those dependencies on cluster nodes by cgcloud. Did you also install Docker manually? If so, that  would be redundant either.

I added a clarifying comment in

https://github.com/BD2KGenomics/toil-scripts/commit/e9a7b78cc72468c2c3a66eea32d620781eb1804d

If you install any Python application anywhere, on your own box or on an EC2 node, you should always, always use a virtualenv. Anyone who recommends anything else is clueless or crazy. But hey, so am I.
