### ISSUE TITLE
Add mock-ups to ADAM/GATK pipelines

### ISSUE THREAD

**Issue by almussel** [BD2KGenomics/toil-scripts#206]
@hannes-ucsc and I discussed this after scrum today.

In mock-up mode, the steps of the pipeline should do the following, given a small fastq and associated bam file (<20mb):

BWA alignment: Downloads input fastq and pre-computed mock.bam file. Renames bam file and writes to the appropriate s3 bucket.
ADAM preprocessing: Runs as usual, but using tiny instances. Produces a preprocessed bam file which is then replaced with an empty bam that is written to s3.
GATK preprocessing: Downloads the input BAM file, writes dummy intermediate files to the jobstore, and writes a blank preprocessed bam file with the appropriate name to s3.
Haplotype caller: Downloads the input preprocessed BAM file, and writes a blank vcf file with the appropriate name to s3.

In addition we will add assertions after the completion of each pipeline step that check that all necessary files are present. These checks will run in both mock-up mode and production mode.

@fnothaft what are your thoughts? I can get started on this today if you think it seems reasonable.

**Comment by fnothaft** [comment]
Use this BAM: http://www.cs.berkeley.edu/~massie/bams/mouse_chrM.bam

**Comment by hannes-ucsc** [comment]
We will be adding an `outputs=` kwarg to `docker_call()` that is a dictionary whose keys are names of expected output files and whose values are either None (a zero length file will be created in mock mode) or a URL (the file will be downloaded and used as the output in mock mode). In production mode, the dictionary will be use to assert the existence of the outputs.

@fnothaft suggested to add an `inputs=` kwarg that specifies the expected inputs. Presence of inputs should be asserted in both mock mode and production mode.

**Comment by almussel** [comment]
@fnothaft it looks like the file you provided is truncated. I tried to view it with samtools and I'm getting:
```
[main_samview] truncated file.
```

**Comment by fnothaft** [comment]
@almussel interesting! I just took a look at this, and it seems to be OK:

```
fnothaft$ samtools view http://www.cs.berkeley.edu/~massie/bams/mouse_chrM.bam | wc
[knet_seek] SEEK_END is not supported for HTTP. Offset is unchanged.
  163064 3681273 59942304
```

Can you send me the command you are running?

**Comment by almussel** [comment]
I downloaded the file to my laptop before running samtools view. When I view it directly it works fine...

**Comment by fnothaft** [comment]
Seems OK yonder over here as well:

```
fnothaft$ wget http://www.cs.berkeley.edu/~massie/bams/mouse_chrM.bam; samtools view mouse_chrM.bam | wc
--2016-03-31 12:18:50--  http://www.cs.berkeley.edu/~massie/bams/mouse_chrM.bam
Resolving www.cs.berkeley.edu... 128.32.244.183
Connecting to www.cs.berkeley.edu|128.32.244.183|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12712625 (12M) [application/octet-stream]
Saving to: 'mouse_chrM.bam'

mouse_chrM.bam                                      100%[====================================================================================================================>]  12.12M  17.1MB/s   in 0.7s   

2016-03-31 12:18:51 (17.1 MB/s) - 'mouse_chrM.bam' saved [12712625/12712625]

  163064 3681273 59942304
```

**Comment by almussel** [comment]
Weird... In any case, I can create the fastq I need so it's fine?

**Comment by almussel** [comment]
Okay I tried it with curl and it's fine. For some reason clicking on the link to download messes it up.

**Comment by fnothaft** [comment]
Hah! Good ol' UC Berkeley IT at work there... Glad to hear that this seems to be resolved now.
