### ISSUE TITLE
Review all asserts

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil-scripts#211]
An `assert` statement is used to catch bugs. We currently abuse them to validate inputs. Those abuses should be changed to raises of specific exceptions.

See comment by @fnothaft to the 1.0 PR.

https://github.com/BD2KGenomics/toil-scripts/pull/208#discussion_r57346105

**Comment by hannes-ucsc** [comment]
```
def _assert(expression,message):
…
```

**Comment by fnothaft** [comment]
A nit, but I would prefer `_require` to `_assert`. This would be consistent with Scala's assertion library, and makes assertions (checking internal state) vs. requirements (checking user inputs) more distinctive.

**Comment by hannes-ucsc** [comment]
Makes sense.

**Comment by jvivian** [comment]
A `require` function is being added to the common lib via #268.  Once it is merged I can work on this.
