### ISSUE TITLE
Add dynamic disk resource allocation for rnaseq_cgl

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil-scripts#216]

**Comment by hannes-ucsc** [comment]
Blocked on promises.

**Comment by hannes-ucsc** [comment]
Depends on https://github.com/BD2KGenomics/toil/issues/729

**Comment by hannes-ucsc** [comment]
Depends on #216

**Comment by hannes-ucsc** [comment]
Depends on #267

**Comment by jvivian** [comment]
@jpfeil — You mind giving me a brief tutorial when you get in?  I should really implement this in all the production pipelines.
