### ISSUE TITLE
Support ICGC Storage System on S3/Ceph in Workflows

### ISSUE THREAD

**Issue by briandoconnor** [BD2KGenomics/toil-scripts#218]
@jvivian this is a longer term goal, if we go with the ICGC storage system we want to make sure workflow inputs/outputs can use this system.

Assigning to Hannes so he can reassign

**Comment by briandoconnor** [comment]
Does this belong in https://github.com/BD2KGenomics/core-operations/issues instead?

**Comment by hannes-ucsc** [comment]
Nope, this is the correct project, @briandoconnor.

**Comment by jvivian** [comment]
Duplicate of #266
