### ISSUE TITLE
Create toil-cluster role that contains all dependencies for all toil-scripts

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil-scripts#22]

**Comment by hannes-ucsc** [comment]
This should make use of the --script option in cgcloud. Some hackery might be necessary to  make sure that `create-toil-cluster` uses the replaced role.

**Comment by hannes-ucsc** [comment]
Unzip, docker, curl, samtools, s3am, boto.

**Comment by hannes-ucsc** [comment]
Samtools should not be in this list and dockerized instead. But a bug in the RNASeq user-script prevents that for now.

**Comment by hannes-ucsc** [comment]
@jpfeil and @arkal: could you list the additional dependencies for your pipelines here?

**Comment by arkal** [comment]
I have none

**Comment by hannes-ucsc** [comment]
I think @dyollluap (Paul) should take this on. He and I talked about this yesterday. The source code should live in toil-scripts.

**Comment by hannes-ucsc** [comment]
s3am and curl are present. boto is provided through Toil. samtools is dockerized.

Closing.
