### ISSUE TITLE
Refactor BWA alignment pipeline to make use_bwakit the default

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil-scripts#225]
bwa_kit is not only faster, but more robust than the other method (thanks @fnothaft ).

**Comment by jvivian** [comment]
Handled in hotfix 1.1, forgot to reference.

**Comment by hannes-ucsc** [comment]
> forgot

In that case paste the commit IDs here.

**Comment by jvivian** [comment]
Misread this ticket when I initially closed.  Currently alignment can progress through two separate paths, one of which appears to be objectively inferior, based on results I've gotten.  This refactor will slim down the alignment pipeline to essentially just call bwa_kit which is not only faster, but less complex and more robust than the other method.
