### ISSUE TITLE
Give the RNASeq CGL pipeline an option to take paired fastq files as inputs rather than tarballs

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/toil-scripts#228]
Here are the reasons why we (the production team) would like this:
1. If we provide the two fastq files as inputs, we can verify that they're roughly the same size and that the names seem to match, which would allow us to identify problem inputs earlier.  If the fastqs are packaged in tarballs, these details are hidden.
2. The batch alignment pipeline takes paired fastqs.  If we can take the same type of inputs consistently, across pipelines, that will simplify production greatly!

**Comment by jvivian** [comment]
@melissacline @Jeltje 

The reason I chose tarballs as the primary input method is:

- Only one input to pull
- Most sequencing data I've seen is a tarball with several fastqs inside, meaning a person is required to unpack the tarball and combine the fastqs into pairs (unless they're being delivered already as fastq pairs).

Good news is (hypothetically),  this is already supported.  The help menu for --config shows: 
"Path to CSV. One sample per line with the format: uuid,url (see example config). '
'URLs follow the format of: https://www.address.com/file.tar or file:///full/path/file.tar.'
' Samples must be tarfiles that contain fastq files. **Alternatively, if your data is'
'not tarred, you can create a CSV of one sample per line: uuid,url1,url2 .  Where url1'
'and url2 refer to urls to the pair of fastq files.'"**

**Comment by hannes-ucsc** [comment]
Already implemented.
