### ISSUE TITLE
Exome variant pipeline reported to be slow

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil-scripts#231]
@dyollluap mentioned this morning that he felt the exome variant calling pipeline was surprisingly slow.

**Comment by jvivian** [comment]
@dyollluap Any chance I could get:

- The launch script used
- Number of samples / Number of workers
- Total run time
- Config list so i can check sample sizes and run one as a test

**Comment by hannes-ucsc** [comment]
@dyollluap please provide the requested info and reopen. TY
