### ISSUE TITLE
exome variant pipeline fails but still gives output files

### ISSUE THREAD

**Issue by dyollluap** [BD2KGenomics/toil-scripts#237]
There were 3 (out of 24) datasets that failed on the toil exome variant pipeline and there were results.tar.gz for all but 1 of the datasets posted to S3. I cannot tell which 3 failed. 

2 suggestions:
- It would be helpful to prevent a dataset that has failed from continuing with any further analysis and not posting any results to S3 (as is done in the other pipelines)
- It would be helpful to get a listing from the stacktrace or an error log of which datasets failed instead of comparing the config and the bucket contents

**Comment by jvivian** [comment]
This is paradoxical — If the sample failed in the pipeline, it cannot upload results to S3 (which is the last step in the pipeline). 

> It would be helpful to prevent a dataset that has failed from continuing with any further analysis and not posting any results to S3 (as is done in the other pipelines)

This is the case in the exome variant pipeline.  Are any of the result tarballs empty? If they are not, then what makes you think the samples failed?  If you have `--retryCount` set in the launch script, seeing a non-deterministic failure for a sample doesn't guarantee it doesn't eventually succeed.

**Comment by dyollluap** [comment]
Paradoxical yes!
All the tarballs uploaded to s3 are > 80MB. Only 1 missing from the anticipated output. 
The final lines in the Stacktrace gave the listing of errors, which affected 3 jobs. The cluster is terminated now, this was a follow up note for the record though I haven't yet cleaned out the jobstore if it's of any value...

**Comment by jvivian** [comment]
It's possible for a single sample to have caused 3 job failures due to job parallelization, which is a bit misleading. 

> It would be helpful to get a listing from the stacktrace or an error log of which datasets failed instead of comparing the config and the bucket contents

I will think on this — I'm adding logging to the refactored RNA-seq pipeline which tells you every step you're on (and the UUID associated).  I'll see if there's any easy way to scrape the log.txt file you get from running the pipeline to compile these for you.

**Comment by jvivian** [comment]
@dyollluap — Closing this issue.

**Comment by hannes-ucsc** [comment]
@dyollluap, feel free to reopen if you're not satisfied with the resolution. @jvivian, I'd prefer if a commit was referenced as a resolution, since you [mention](https://github.com/BD2KGenomics/toil-scripts/issues/237#issuecomment-210665271) making changes to the code.
