### ISSUE TITLE
Setup CI for exome variant pipeline

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil-scripts#238]

**Comment by jvivian** [comment]
Waiting on Tumor/Normal test inputs from @jpfeil

**Comment by hannes-ucsc** [comment]
Blocked on https://github.com/BD2KGenomics/protect/issues/6

**Comment by jvivian** [comment]
@jpfeil Where are the reads you used for the tumor / normal samples you implemented in the ProTect CI?

**Comment by jpfeil** [comment]
pimmuno-test-data/CI_test_input/reads/

Normal DNA: ERR01639X_HCC1954BL.chr6.1.fq.gz
Tumor DNA: ERR01636X_HCC1954.chr6.1.fq.gz

Here is a link to the SRA page:
http://www.ncbi.nlm.nih.gov/sra/?term=ERR016361
