### ISSUE TITLE
Remove redundant buckets for toil-scripts project

### ISSUE THREAD

**Issue by jpfeil** [BD2KGenomics/toil-scripts#25]
I moved pipeline inputs into cgl-pipeline-inputs, so we do not need project specific buckets anymore.

**Comment by hannes-ucsc** [comment]
The name of the project is actually ``toil-scripts``, not ``toil-script``.

**Comment by hannes-ucsc** [comment]
Thank you. Now if you could file a PR against toil-scripts that adjusts the URLs in the wrapper shell scripts to the new bucket. And could you paste the bucket name here?

**Comment by hannes-ucsc** [comment]
What's the relationship between this issue and BD2KGenomics/toil#495?

**Comment by jpfeil** [comment]
We are keeping the buckets around until we have tested the new input urls.

**Comment by hannes-ucsc** [comment]
I see. So which ticket is used to track the update to the wrapper scripts that I mentioned above?

**Comment by jvivian** [comment]
@jpfeil Once a PR is submitted against toil-scripts to update the "launch" bash scripts to the new URLs I think this ticket can be closed.  (Make sure the PR is against the 1.0.7 branch).

Shortly we'll be running the rna-seq for Treehouse and the variant pipeline for WCDT, I'll do a quick sanity check that tests that the URLs before a production run.

**Comment by hannes-ucsc** [comment]
Still need a ticket for the actual change to the wrapper scripts or was this done already?

**Comment by jpfeil** [comment]
Depends on issue #28

**Comment by hannes-ucsc** [comment]
#28 is closed so this is unblocked. Assigning to @jvivian since @jpfeil is rotating in a different lab.
