### ISSUE TITLE
BWA refactor broke ADAM/GATK pipeline

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/toil-scripts#253]
The [recent BWA refactor](https://github.com/BD2KGenomics/toil-scripts/commit/32139555267234b0f39a9ce9400d5eafb601b085) broke the interface that the ADAM/GATK pipeline was using. We should refactor the ADAM/GATK pipeline to use the refactored pipeline.

**Comment by jvivian** [comment]
Ah, apologies — I only saw that two imports were affected which I replaced with common lib references.

**Comment by fnothaft** [comment]
No worries! I'm reverting my local back to before the commit came in, and I'll patch this later.

**Comment by jvivian** [comment]
@fnothaft Is this still bjorken?

**Comment by fnothaft** [comment]
Not sure, need to review recent changes.

**Comment by fnothaft** [comment]
Fixed by https://github.com/BD2KGenomics/toil-scripts/commit/ba557211f36dbd5b2b74718fa7c496c4c49fa1d4.
