### ISSUE TITLE
Sanity check new URLs for pipelines

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil-scripts#26]
URLs were updated, ensure that they still work. 

- [ ] Batch Alignment
- [ ] RNA-Seq
- [ ] Variant

**Comment by hannes-ucsc** [comment]
This is why we need integration tests for each of the scripts in toil-scripts: so we don't need to manually test the scripts after each change to the script or their static inputs.

**Comment by jvivian** [comment]
@hannes-ucsc -- That's what #226 is addressing.  I created this ticket since the pipelines will likely be needed prior to #226 completion.   (Not sure how to cross-link issues between repos, but the issue is under the wrong project: https://github.com/BD2KGenomics/toil/issues/226)

**Comment by hannes-ucsc** [comment]
Depends on #28
