### ISSUE TITLE
Add ICGC Storage System support

### ISSUE THREAD

**Issue by briandoconnor** [BD2KGenomics/toil-scripts#266]
Need to add support so Toil workflows in Toil-Scripts can read/write data to the ICGC Storage System we're using on AWS.  Also, this includes supporting the automatic creation of the JSON used by the metadata tracking system.

**Comment by briandoconnor** [comment]
Start with RNASeq-CGL

**Comment by jvivian** [comment]
Superseded by BD2KGenomics/toil-lib#69
