### ISSUE TITLE
Release 2.0.0 of toil-scripts

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil-scripts#267]
This will be the first pip installable release. Create release then hand off to production. Then change setup.py on master to refer to unstable Toil.

Blocked on #245

**Comment by hannes-ucsc** [comment]
Production team will verify release.

**Comment by jvivian** [comment]
First stable pip installable release for production pipelines.  Consistent configuration and invocation across the production pipelines. 

@melissacline — May i remove the production label from the UNC pipeline or is there still demand for it?
