### ISSUE TITLE
Refactor MuTect to run by chromosome

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil-scripts#271]

**Comment by arkal** [comment]
https://github.com/BD2KGenomics/protect/issues/27

**Comment by jvivian** [comment]
MuTect runs single-threaded.  I'll be borrowing @arkal's method of splitting the sample up by chromosome.

**Comment by jvivian** [comment]
Cleaning up tickets — Exome pipeline is not in production and is not part of my current research so I'm closing.
