### ISSUE TITLE
Modify Docker Run to fix root issue

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil-scripts#273]

**Comment by jvivian** [comment]
As discussed in a meeting today, we want to be agnostic about the origin of our docker containers, which means handling the Docker root ownership issue ourselves.  

Here's a starting point @hannes-ucsc 

- Start container in the background and keep running
    - ` docker run --name test -d ubuntu tail -f /dev/null`
- Run command (and block, although can be run without blocking)
    - `docker exec test sleep 5`
- Run command to deal with ownership issues
    - Can either be a docker command to chown or something else?
- Kill container
    - `docker kill test`

**Comment by hannes-ucsc** [comment]
The problem is that for a given image you don't know what the entry point is, so you don't know what to pass to exec.

How about we `docker exec … chmod` using a different, minimal image (say, ubuntu) that `-v`-mounts the same data directory.

**Comment by jvivian** [comment]
@hannes-ucsc and I discussed this and our solution is to run the tool image a second time, overwriting the entry point, to `chown` the mount directory where output is placed by the first tool.
