### ISSUE TITLE
minor error: incorrect path to bash shell in batch_alignment readme

### ISSUE THREAD

**Issue by tkdagdelen** [BD2KGenomics/toil-scripts#274]
This is very minor. Just wanted to point out that in the Readme for batch_alignment, the path to the shell script at the bottom is /toil-scripts/src/toil_scripts/spladder_pipeline/launch_bwa_hg38_no_alt.sh but it seems like it should be /toil-scripts/src/toil_scripts/batch_alignment/launch_bwa_hg38_no_alt.sh

**Comment by jvivian** [comment]
Oops, thanks for catching that!  Appreciate it =)  I'll fix it in my next PR.
