### ISSUE TITLE
Improve readability of configs (exome/RNA)

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil-scripts#290]
Having comments on the same line as YAML inputs means once the user fills in options the formatting gets all yucko.

**Comment by hannes-ucsc** [comment]
Yes, editing the generated config is a pain. I should just have to remove a single `#` character to turn an example into a valid config line.

**Comment by hannes-ucsc** [comment]
Also file name should end in `.yaml`, not `.config`. Or `.config.yaml` but that may be overkill.
