### ISSUE TITLE
Add RNA-SeQC to RNA-Seq Pipeline

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil-scripts#3]
_From @jvivian on August 10, 2015 23:26_

null

_Copied from original issue: BD2KGenomics/toil#223_

**Comment by jvivian** [comment]
I added RSeQ_QC to the pipeline and nobody has requested anything in addition so I will close this ticket.  I'll open a new ticket if that changes and somebody does request additional QC.
