### ISSUE TITLE
Factor out hardcoded `/mnt/ephemeral` references

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/toil-scripts#315]
This came to mind while reviewing [a line](https://github.com/BD2KGenomics/toil-scripts/blob/23bc4702c5b2007ccdfcbf29ee5c132723728a70/src/toil_scripts/rnaseq_cgl/test/test_rnaseq_cgl.py#L13) that was referenced in #314. We've got a variety of places in the repo where we've hardcoded `/mnt/ephemeral` into our scripts, under the assumption that we'll always be running on a cgcloud configured AWS box. This is fine and dandy, until you're running outside of AWS.

I feel like we could roll this into some sort of `get_ephemeral_directory` function that would:

* Look for the existence of a TOIL_EPHEMERAL environment variable
* Barring that, look for the existence of /mnt/ephemeral
* And finally, barring that, call to https://docs.python.org/2/library/tempfile.html or something

**Comment by jvivian** [comment]
+1  — the hardcoded `/mnt/ephemeral` makes running tests locally a hindrance.

@fnothaft — Where should the `get_ephemeral_directory`  function live? 

@hannes-ucsc — what is your preferred implementation for this?

**Comment by fnothaft** [comment]
> @fnothaft — Where should the get_ephemeral_directory function live?

I'm feeling somewhere in `toil_scripts.lib`? Perhaps `toil_scripts.lib.files` or a new module `toil_scripts.lib.directories`? Also, what's the news with the toil-lib package? This would be an ideal candidate to go there, IMO.

**Comment by hannes-ucsc** [comment]
Cgcloud sets (and ad Toil reads) TOIL_WORKDIR . It points to /var/lib/toil which is bind-mounted by cgcloud to /mnt/ephemeral/var/lib/toil if present. I think it is ok to create a uniquely named directory in there.

**Comment by hannes-ucsc** [comment]
And yes, extract a function to toil_scripts/lib/__init__.py. But don't reference `ephemeral` in the name.

**Comment by fnothaft** [comment]
+1, that SGTM
