### ISSUE TITLE
Support mock_mode in BWA pipeline

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil-scripts#321]
While refactoring I noticed code support for mock_mode, but the mock argument is never invoked in `docker_call`, so it doesn't do anything at the moment.

**Comment by almussel** [comment]
`mock_mode` is invoked with the `TOIL_SCRIPTS_MOCK_MODE` environment variable, which causes `docker_call` to run in `mock_mode`. The `mock` argument is only used to override the environment variable if necessary (this is used in the `adam_preprocessing` pipeline to force the spark containers to run even in `mock_mode`).

**Comment by jvivian** [comment]
> mock_mode is invoked with the TOIL_SCRIPTS_MOCK_MODE environment variable, which causes docker_call to run in mock_mode. The mock argument is only used to override the environment variable if necessary (this is used in the adam_preprocessing pipeline to force the spark containers to run even in mock_mode).


Oh awesome, thanks @almussel ! I missed the call to `mock_mode` in `docker_call` that checks for the env variable.
