### ISSUE TITLE
Spark master IP retrieved from wrong node

### ISSUE THREAD

**Issue by almussel** [BD2KGenomics/toil-scripts#327]
The `__init__` method of a service is not necessarily called from the same node as the service is actually run on. Because of this, the master IP of the spark cluster can't be determined in the `__init__` method. This manifests itself in connection failures once the service is running.

**Comment by almussel** [comment]
This was supposed to be a toil issue. Nvm.

**Comment by fnothaft** [comment]
This was fixed already in toil: https://github.com/BD2KGenomics/toil/pull/1008.

**Comment by almussel** [comment]
Ahh, forgot to update toil. Thanks!
