### ISSUE TITLE
Implement encryption key management service

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil-scripts#34]
The main purpose is to prevent us from having to distribute the master key to the operators within the core group, i.e. the people running the pipelines on controlled-access data. The master key should only be in the possession of a very limited number of people. But most importantly, you shouldn't have to pass the most important secret to give an operator access to the system. 

The solution should also be simple and low-tech.

Instead of GPG, I think we should piggy-back on SSH keys because everyone is bound to have one already. Here is the outline:

1) A user requests to be authorized by sending their public key to the key admin. The key admin is in possession of the master key.

2) The key admin generates a plaintext token (random string + user_id + expiration) using the service's public key and the users public key and sends the twice-encrypted token back to the user.

3) The key admin uses the plaintext token to encrypt the master key and deposits the encrypted master key on the machine running the service. This will be known as the user-specific master key.

4) The user sends a request to the key management service containing the token and a list of URLs. The token is the once-decrypted token, i.e. it is still encrypted with the service's public key.

5) Using its private key, the service decrypts the token into plain text, validates the token, loads the user-specific master key into memory and then uses the token to decrypt the user-specific master key. This will result in the clear-text master key in memory on the machine running the service. It then uses the plain-text master key to derive a per-file key for each of the submitted URLs and sends the result back. TBD: Should we use a nonce for the derivation?

The resulting per-URL keys could be encrypted using the once-encrypted token or we could rely the security of the underlying channel through which request and response are communicated, i.e. HTTPS. Or a combination of both.

TBD: Access control to the service machine.

**Comment by jvivian** [comment]
I'd love an explanation of this in person next time we meet.  I get the general premise but am a little hazy on a few of the details.

**Comment by hannes-ucsc** [comment]
I revised the text a bit. There were a few errors in it.

**Comment by hannes-ucsc** [comment]
Obsoleted by ICGC storage system.
