### ISSUE TITLE
Exome - Refactor mean insert size

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil-scripts#347]
The function was taken from the MC3 pipeline and should be rewritten or replaced with something better.

**Comment by fnothaft** [comment]
I have some code upstream in ADAM that we could use for this, IIRC. LMK if you want to assign it to me.

**Comment by jvivian** [comment]
If it's easier for you to point me to it or paste a snippet here I don't mind doing it, otherwise feel free to self-assign.

**Comment by fnothaft** [comment]
I'll ping this later this week; need to clean it up a bit.

**Comment by jvivian** [comment]
Cleaning up tickets — Exome pipeline is not in production and is not part of my current research so I'm closing.
