### ISSUE TITLE
Installation instructions are misleading

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil-scripts#348]
https://github.com/BD2KGenomics/toil-scripts/tree/master/src/toil_scripts/rnaseq_cgl#installation

When using `virtualenv --system-site-packages` one should not `pip install toil`.

**Comment by hannes-ucsc** [comment]
Also, the Dependencies section should precede Installation

**Comment by jvivian** [comment]
> When using virtualenv --system-site-packages one should not pip install toil.

What should one do?
