### ISSUE TITLE
Minor test_rnaseq_cgl issues

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil-scripts#352]
* Unused parameter tmpdir
* `finally` clause [piggy-backs](https://github.com/BD2KGenomics/toil/wiki/Python-Dos-and-Don'ts#dont-piggy-back-resource-deallocation)

**Comment by hannes-ucsc** [comment]
* shouldn't hard-code workdir but use Python's `tempfile` module (set TMPDIR at the beginning of the build)

**Comment by hannes-ucsc** [comment]
Ignore previous comment.

**Comment by jvivian** [comment]
@hannes-ucsc — I can fix this in 2.0.  I'm in the middle of moving so I haven't been as quick to get that out as I would've liked.
