### ISSUE TITLE
jenkins.sh shouldn't install bd2k-python-lib

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil-scripts#360]
… since that is a "provided" dependency like Toil.

**Comment by hannes-ucsc** [comment]
Sorry, wasn't thinking right. BPL shouldn't be installed explicitly because it is a dependency provided transitively by Toil. setup.py already asserts that the version provided by Toil is acceptable. Installing it explicitly is risking to break Toil.

**Comment by jvivian** [comment]
Ok, I thought we had discussed this and you said never have transitive dependencies in case they change — I guess since we're the ones writing both packages we'll know BPL will never _not_ be a Toil dependency.

**Comment by hannes-ucsc** [comment]
Yes, I remember saying that. I was wrong. The problem I see is that T advances the version of its BPL dependency, and TS's `jenkins.sh` then downgrading BPL it to what TS incorrectly assumes T provides. This could break tests (false positive), but it could also hide legitimate failures (false negatives).
