### ISSUE TITLE
Curl called on S3 URL in exome pipeline

### ISSUE THREAD

**Issue by JakeNarkizian** [BD2KGenomics/toil-scripts#364]
[log.txt](https://github.com/BD2KGenomics/toil-scripts/files/367591/log.txt)
log is too long to post here. See attached script generated text file.

**Comment by jvivian** [comment]
Headers are being invoked, meaning this is an identical issue to: https://github.com/BD2KGenomics/toil-scripts/issues/361

**Comment by hannes-ucsc** [comment]
@jvivian, If the issue is systemic to toi-scripts, track this as a single issue and close this one as a duplicate.

**Comment by jvivian** [comment]
Duplicate of #361
