### ISSUE TITLE
Update cgcloud and toil-box AMIs

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil-scripts#37]
BD2KGenomics/toil#416 and BD2KGenomics/toil#499 plus various other issues have been resolved. It's time to update the AMIs used for the Toil runs.

**Comment by hannes-ucsc** [comment]
@jvivian: Is this done?

**Comment by jvivian** [comment]
yup! created a new toil-latest-box image day before yesterday.
