### ISSUE TITLE
Confirm no issues with --restart

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil-scripts#373]
Trying to restart an RNA-seq pipeline run on a mesos leader/worker with an AWS jobstore resulted in an import error being unable to find `toil_scripts/rnaseq_cgl/rnaseq_cgl_pipeline`. 

Jake — When testing the 2.0.1 release, making resuming a pipeline part of your tests.

toil-scripts was installed in a virtualenv on the leader, with `--system-site-packages`

**Comment by JakeNarkizian** [comment]
*Note to self*: Also request bam and wiggle files

**Comment by jvivian** [comment]
@JakeNarkizian — able to reproduce?

**Comment by jvivian** [comment]
@JakeNarkizian — Update?

**Comment by JakeNarkizian** [comment]
@jvivian could not reproduce on fresh cluster. see [core-operations #58](https://github.com/BD2KGenomics/core-operations/issues/58).
