### ISSUE TITLE
Cherrypick bug commits to master

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil-scripts#375]

**Comment by hannes-ucsc** [comment]
You don't really need a special ticket for CP'ing bugfixes from a release branch to master. Assuming that each CP'ed commit refers to the issue it resolves, when you committed/merged them into the releases/2.0.x branch, GH did nothing, the tickets remained open. This should serve as a reminder to CP them into master. When you then actually merge the CPs into master, GH will close those tickets for you.

**Comment by jvivian** [comment]
Great point, I realized that after I started the CP.

**Comment by jvivian** [comment]
@hannes-ucsc — In the case where I am putting these CPs on a branch to PR against master, if I'm not opening a ticket (as you suggested), what naming convention should I use for the branch?

**Comment by hannes-ucsc** [comment]
I haven't found a good convention yet. How about

`issues/123-456-789-cherrypick-to-master`

With PRs that only have one CP in them, I tried various schemes. The best one so far was

`issues/123-bla-bla-bla/releases/2.0.x` for the PR against `releases/2.0.x`
`issues/123-bla-bla-bla/master` for the PR against master  

For a PR with multiple CPs the equivalent would be 

issues/123-bla-bla-bla/releases/2.0.x
issues/456-bla-bla-bla/releases/2.0.x
issues/789-bla-bla-bla/releases/2.0.x
issues/123-456-789/master

That could be codified pretty easily.

**Comment by hannes-ucsc** [comment]
One of git's quirks is that if you have a branch called `foo` you can't also have a branch called `foo/bar`. Don't know why exactly.
