### ISSUE TITLE
rna-seq-cgl stalls for a while

### ISSUE THREAD

**Issue by JakeNarkizian** [BD2KGenomics/toil-scripts#382]
```
toil.batchSystems.mesos.batchSystem: Although there are queued jobs, none of them could be run with theoffers extended to the framework.
```
The workflow eventually completed but this went on for quite some time, assuming it is not expected behavior. 

See my comments [here](https://github.com/BD2KGenomics/core-operations/issues/53) for manifest and config.

See attached [log file](https://github.com/BD2KGenomics/toil-scripts/files/384865/log.txt).

**Comment by jvivian** [comment]
This is a non-issue, just a reoccurring message that no additional offers can be extended.

**Comment by hannes-ucsc** [comment]
Agree with closing this. However, @JakeNarkizian, this is a bit noisy and I also noticed that it is logged once for every offer and therefore node in the cluster. Can you open a ticket against Toil?
