### ISSUE TITLE
Add clinical variant annotation to germline 

### ISSUE THREAD

**Issue by jpfeil** [BD2KGenomics/toil-scripts#401]

**Comment by fnothaft** [comment]
Linking this to #335, #280, https://github.com/BD2KGenomics/cgl-docker-lib/issues/163. @jpfeil can you fill this in with the tools you are going to run in the pipeline?

**Comment by jpfeil** [comment]
I will add Oncotator to the pipeline (https://github.com/broadinstitute/oncotator).
