### ISSUE TITLE
toil-rnaseq expects s3 output dir

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/toil-scripts#402]
I want to get output locally, so in my config:
`output-dir: /mnt/test_cgl1/out1`

Error:
```
File "/home/ubuntu/venvs/cgl/local/lib/python2.7/site-packages/toil_scripts/rnaseq_cgl/rnaseq_cgl_pipeline.py", line 151, in rsem_quantification
           if config.s3_output_dir:
       AttributeError: 'Namespace' object has no attribute 's3_output_dir'
```
Versions:
```
bd2k-python-lib (1.14a1.dev29)
toil (3.3.1)
toil-scripts (2.1.0a1.dev478)
```
[Full log file] (http://hgwdev.cse.ucsc.edu/~jeltje/toil/log.1)
[Config file] (http://hgwdev.cse.ucsc.edu/~jeltje/toil/config1.txt)
[Manifest file] (http://hgwdev.cse.ucsc.edu/~jeltje/toil/manifest1.txt)

**Comment by jvivian** [comment]
Please test release versions not development versions, this was addressed here: https://github.com/BD2KGenomics/toil-scripts/pull/392
