### ISSUE TITLE
add full FastQC output to toil-rnaseq

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/toil-scripts#404]
Currently, `fastqc: true` results in a single HTML file per input fastq. However, we're working on a cohort QC pipeline that uses both the fastqc_data.txt file and the separate .png image files for each sample. Can these be added to the tar file?

**Comment by jvivian** [comment]
FastQC only has options for saving output as a zip — that ok?

**Comment by Jeltje** [comment]
Sure!

**Comment by jvivian** [comment]
@Jeltje — I'm guessing you need this as part of the 2.0.x release?

**Comment by Jeltje** [comment]
@jvivian Yes, because the first batch we plan to run is for CKCC and they care.
