### ISSUE TITLE
toil-rnaseq cutadapt error when using local input fastq

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/toil-scripts#405]
`toil-scripts (2.0.5)`

Trying to run with local fastq, so the manifest looks like this:
`fq      paired  localin file:///mnt/test_cgl1/testinput/C021_0006_002221_BR_Whole_T2_K1STX_A12445_000_R1.fastq.gz,file:///mnt/test_cgl1/testinput/C021_0006_002221_BR_Whole_T2_K1STX_A12445_000_R2.fastq.gz`

I did not change the cutadapt settings in the config file, but I get this error:
` TypeError: run_cutadapt() takes exactly 5 arguments (4 given)`

[full log](http://hgwdev.cse.ucsc.edu/~jeltje/toil/log.2)
[config](http://hgwdev.cse.ucsc.edu/~jeltje/toil/config2.txt)
[manifest](http://hgwdev.cse.ucsc.edu/~jeltje/toil/manifest2.txt)

**Comment by jvivian** [comment]
@Jeltje — FastQC only has options to save the output as a zip (other than HTML).  That ok?

**Comment by jvivian** [comment]
@Jeltje — Thanks! I'll get a fix up once I'm up on campus, should only take a few minutes.
