### ISSUE TITLE
toil-rnaseq cutadapt error when using local input fastq (again)

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/toil-scripts#410]
Same inputs as https://github.com/BD2KGenomics/toil-scripts/issues/405

using `2.0.6`
This time the error is `cutadapt: error: at line 1, expected a line starting with '@'`

The inputs are fastq.gz, so maybe there's a problem with extraction? The input files are from an extracted s3 tar file I used in an earlier (passed) test (and line 1 does start wit '@')

[log file](http://hgwdev.cse.ucsc.edu/~jeltje/toil/log.3)

**Comment by jvivian** [comment]
Thanks @Jeltje — looking at this now.
