### ISSUE TITLE
Produce inputs for new RNA-Seq pipeline

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil-scripts#46]

**Comment by jvivian** [comment]
All inputs are based on HG38 human reference genome and gencodes v23 annotations

HG38: http://hgdownload.cse.ucsc.edu/goldenPath/hg38/bigZips/
gencodev23: http://www.gencodegenes.org/releases/23.html

- [x] Star Index
- [x] RSEM reference
- [ ] Kallisto index

**Comment by jvivian** [comment]
All inputs for the rnaseq pipeline are here:
s3://cgl-pipeline-inputs/rnaseq_cgl/

- [x] Create STAR inputs
    - Command:
        - sudo docker run -v $(pwd):/data quay.io/ucsc_cgl/star --runThreadN 32 --runMode genomeGenerate --genomeDir /data/genomeDir --genomeFastaFiles hg38.fa --sjdbGTFfile gencode.v23.annotation.gtf
    - GTF was taken from gencode (v23)
        - http://www.gencodegenes.org/releases/23.html
    - hg38.fa was taken from UCSC
        - http://hgdownload.cse.ucsc.edu/goldenPath/hg38/bigZips/
    - StarIndex is located at:
        - https://s3-us-west-2.amazonaws.com/cgl-pipeline-inputs/rnaseq_cgl/starIndex.tar.gz

    - STAR inputs follow ENCODE’s best practices
- [x] Build Kallisto Index for HG38
    - Command:
        - sudo docker run -v $(pwd):/data quay.io/ucsc_cgl/kallisto index -i hg38.gencodeV23.transcripts.idx transcriptome_hg38_gencodev23.fasta
    - Get transcriptome for HG38
        - Requires gencodev23.bed with the following regions REMOVED

            - chrY:10,000-2,781,479
            - chrY:56,887,902-57,217,415
    - [Kallisto.idx located in s3](https://s3-us-west-2.amazonaws.com/cgl-pipeline-inputs/rnaseq_cgl/kallisto_hg38.idx)
- [x] Generate “RSEM_REF” for HG38
    - Command:
        - sudo docker run -v $(pwd):/data --entrypoint=rsem-prepare-reference jvivian/rsem -p 4 --gtf gencode.v23.annotation.gtf hg38.fa hg38
    - rsem_ref.tar.gz located at:
        - https://s3-us-west-2.amazonaws.com/cgl-pipeline-inputs/rnaseq_cgl/rsem_ref_hg38.tar.gz
- [x] Containerize CutAdapt
    - List of [Illumina adapter sequences](https://support.illumina.com/content/dam/illumina-support/documents/documentation/chemistry_documentation/experiment-design/illumina-adapter-sequences_1000000002694-00.pdf)
    - quay.io/ucsc_cgl/cutadapt:1.9--6bd44edd2b8f8f17e25c5a268fedaab65fa851d2
- [x] Containerize RSEM
    - quay.io/ucsc_cgl/rsem:1.2.25--d4275175cc8df36967db460b06337a14f40d2f21

**Comment by zhaleh-safikhani** [comment]
Can I ask how you've created transcriptome_hg38_gencodev23.fasta? It is not the transcripts fasta file downloadable from Gencode!? Do you have the procedure you followed to create it? Can you share?

**Comment by jvivian** [comment]
The STAR, RSEM, and Kallisto inputs can be located on [Synapse](https://www.synapse.org/#!Synapse:syn5882333/files/).  I'm also close to finishing a PR that will allow users to construct their own inputs from any genome/annotation file.
