### ISSUE TITLE
Investigate obtaining cosmic.vcf for hg38

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil-scripts#49]
Cosmic is useful for MuTect calling:

"In contrast, COSMIC is a more highly validated resource, so it is used essentially as a whitelist to "rescue" candidate mutations that would otherwise be rejected for being in the panel of normals and/or dbSNP. We expect that anything that is really somatic that is flagged as such in dbSNP will also be in COSMIC, so we can rely on COSMIC to rescue those sites."

**Comment by arkal** [comment]
Not very hard to do. Make an account on sanger and download from their website. Alternatively, you can use this to get it
https://github.com/arkal/docker_scripts/blob/master/prepare.py#L788-L840

you just need to provide a username and password form Sanger

**Comment by jvivian** [comment]
@arkal Thanks!
