### ISSUE TITLE
Run variant pipeline with hg38 test inputs

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil-scripts#54]
**Note**:  This ticket is blocked until we get an hg38 validation pair from Adam Ewing.
Produce a test pair of hg38 aligned inputs and then produce the following VCFs:
- [ ] No HG38 inputs
- [ ] with 1000G Snps + Indels
- [ ] with DBSNP
- [ ] with cosmic
- [ ] 1000G + DBSNP
- [ ] 1000G + Cosmic
- [ ] DBSNP + Cosmic
- [ ] All hg38 inputs
  1. Cosmic VCF comes from [Sanger](http://cancer.sanger.ac.uk/cosmic/download)
  2. Other HG38 inputs are coming from this [liftover dir](https://drive.google.com/folderview?id=0B3NI2BxPvRUwflZqbmtBX0xFWWRMNmh5WHZVTm4zcHZRYXcwOWQ4a05uZlhETW95NHlJczg&usp=sharing#list)

**Comment by fnothaft** [comment]
@jvivian Are you doing this for Mutect & GATK, or would it be helpful for me to run it for GATK?

**Comment by jvivian** [comment]
@fnothaft -- I'll be running this through the T/N variant calling which includes the GATK pre-processing, but uses MuTect for the actual variant calls.

**Comment by jvivian** [comment]
I'm blocked on this until we get working HG38 inputs — which means until someone has the bandwidth to look into this or Broad decides to release a bundle for HG38.

**Comment by fnothaft** [comment]
I assembled GRCh38 inputs, if those are sufficient for you.

**Comment by jvivian** [comment]
> I assembled GRCh38 inputs, if those are sufficient for you.

Awesome, this was a couple months ago and I was bit hazy and where we left off as every method I tried ended up failing.   Are the GRCh38 inputs in the BD2K bucket?

**Comment by fnothaft** [comment]
Yeah, they're in the GRCh38_variant subdirectory, iirc. I can get you full URLs if needed.

**Comment by jvivian** [comment]
Cleaning up tickets — Exome pipeline is not in production and is not part of my current research so I'm closing.
