### ISSUE TITLE
Fix GATK container (add java ENV)

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil-scripts#6]

**Comment by hannes-ucsc** [comment]
The variable name should be `JAVA_OPTS`. That's a widely accepted convention.

**Comment by jvivian** [comment]
Added a statement: `java $JAVA_OPTS -jar /path/to/jar.jar` in the wrapper that will allow a user to specify any number of java options.  In concert with docker, this is achieved by using the `-e` flag.   

Example:
`docker run -e JAVA_OPTS=-Xmx15g computationalgenomicslab/gatk <parameters>`
