### ISSUE TITLE
Running into some resource allocation problems

### ISSUE THREAD

**Issue by dgaston** [BD2KGenomics/toil-scripts#60]
Since there is no general help forum for Toil or Toil scripts and it is in heavy development, I thought this would be the best place to ask. I have been working on porting over my existing pipeline work to Toil due to its broad support for Mesos. I am currently running this pipeline just locally. I wanted to do something a little different because I re-use many of the same methods in different pipelines so all of the methods live in their own project and are then imported into the pipeline script where I construct the workflow and graph using wrapJobFn() to define all of the jobs and then use the addJob() method to chain them together for maximum flexibility. You can see this in this repo: https://github.com/dgaston/ddbio-ngsflow.

All of my wrapper methods are in ngsflow and the workflow-* scripts are the various pipelines. workflow-somatic-amplicon.py is the current one I am testing.

The problem I am having is that the jobs don't seem to be respecting the resource allocations. For instance I am specifying --maxCores of 4, in my configuration input I specify that BWA should use 4 cores and so that is passed to the cores keyword argument in wrapJobFn(). However when executing I have four different BWA jobs, each multithreaded to 4 threads running (4 different samples) as well as two other jobs executing. It was my understanding that in this case there should only be a single BWA job executing at a time, as each BWA job should be requesting 4 cores out of a max of 4 cores allowed to toil. I see similar issues with memory usage.

Any help would be appreciated.

**Comment by hannes-ucsc** [comment]
This issue was moved to BD2KGenomics/toil#598
