### ISSUE TITLE
Build new GATK inputs for hg38

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil-scripts#63]
Sadly the liftover files from [here](https://drive.google.com/folderview?id=0B3NI2BxPvRUwflZqbmtBX0xFWWRMNmh5WHZVTm4zcHZRYXcwOWQ4a05uZlhETW95NHlJczg&usp=sharing#list) do not work and others have run into the same issues I did.

After perusing some other options I'm going to try and follow [this page](https://wabi-wiki.scilifelab.se/display/SHGATG/gatk+bundle+in+hg38) and [this makefile](https://bitbucket.org/scilifelab-lts/hg38make/overview)

**Comment by jvivian** [comment]
Thanks to @melissacline , I no longer have to do this, yay!

**Comment by fnothaft** [comment]
Files are in process of upload to `s3://cgl-pipeline-inputs/variant_grch38`.
