### ISSUE TITLE
Fix bug with piping from samtools container

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil-scripts#67]
I want to add Pindel to the exome pipeline, and one of the steps is creating a config for pindel with insert sizes of each of the bams.   I want to avoid adding a non-Docker dependency to the pipeline.

This command works great:
`samtools view -f2 $FILE | head -1000000 | awk '{s+=sqrt($9^2); i+=1} END {print s/i}'`

This command has several problems:
`sudo docker run --rm -v $(pwd):/data quay.io/ucsc_cgl/samtools view -f2 /data/pair9.tumor.bam | head -1000000 | awk '{s+=sqrt($9^2); i+=1} END {print s/i}'`

This gives me a broken pipe (and the correct answer). Samtools and docker.io continue to run, and no further invocations will work.  I can stop it with sudo docker stop $(sudo docker ps -a -q), but that will kill every container running on the instance and is a hacky solution to boot.

**Comment by hannes-ucsc** [comment]
Try adding `--log-driver=none` to the `docker run` command line.

Also, I'm surprised by your reference to docker.io. CGCloud switched from the docker.io package to the one from Docker's own Debian package repo, i.e. the one that is used by the official get.docker.com shell script.

**Comment by jvivian** [comment]
Oops, good catch @hannes-ucsc , my test instance was running an old version.  

I've tried:
- newest version of Docker
- switching to the newest version of samtools
-  `--log-driver=none`
-  `-a stdout`

I found a workaround, but it's inelegant:

`sudo docker run --name=bad_docker_pipe_bad -v $(pwd):/data quay.io/ucsc_cgl/samtools view -f2 /data/pair9.tumor.bam | head -1000000 | awk '{s+=sqrt($9^2); i+=1} END {print s/i}' > insert.txt; sudo docker rm -f bad_docker_pipe_bad`

**Comment by hannes-ucsc** [comment]
What's the intent behind using `head`? Do you still get the broken pipe error if you remove it?

In a Toil pipeline I would replace both `head` and the `awk` with equivalent Python code.

And I think `head -100` is deprecated in favor of `head -n 100`.

**Comment by jvivian** [comment]
> What's the intent behind using head? Do you still get the broken pipe error if you remove it?

Nice idea, that worked.  The addition of `head` was for speed, which is an order of magnitude faster.

```
$ time samtools view -f2 pair9.normal.bam | head -1000000 | awk '{s+=sqrt($9^2); i+=1} END {print s/i}'

174.933
real	0m2.820s

$ time samtools view -f2 pair9.normal.bam | awk '{s+=sqrt($9^2); i+=1} END {print s/i}'

173.812
real	3m8.708s

$ time sudo docker run --log-driver=none --rm -v $(pwd):/data quay.io/ucsc_cgl/samtools view -f2 /data/pair9.tumor.bam | awk '{s+=sqrt($9^2); i+=1} END {print s/i}'

173.817
real    3m11.199s
```

**Comment by hannes-ucsc** [comment]
I think head does a hard close on stdin which, if that input is some other process' stdout, could cause problems if that process isn't prepared to handle the resulting broken pipe signal. Here the writing process is actually docker, not samtools. Can you restrict `samtools view` through some other means, like one of the the `-LrRqlmfF` flags?

**Comment by jvivian** [comment]
Closing since Pindel isn't in the exome variant pipeline
