### ISSUE TITLE
BAM upload to S3 does not work

### ISSUE THREAD

**Issue by dyollluap** [BD2KGenomics/toil-scripts#89]
New image was created on January 18th, tested with 5 datasets that have previously successfully been processed with the unc-rna-seq pipeline. 

I tested it with 2 different versions of the rnaseq_unc_pipeline.py 
a) the same version as had previously successfully processed, only adding the --upload_bam_to_s3
b) the most recent version

**Comment by Jeltje** [comment]
Did you check that samtools and unzip are available on your workers? This tripped me up, but I hadn't run the pipeline before.

**Comment by dyollluap** [comment]
I have samtools, unzip and curl installed on all the workers

**Comment by jvivian** [comment]
Do you have a stack trace?  Did the rest of the pipeline finish and just the upload step fail?

**Comment by hannes-ucsc** [comment]
Please provide input and reopen.
